<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" 
xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" 
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:tns="http://www.djbikerepair.org/BikeRepairService/" 
xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" 
xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:xsd="http://www.djbikeshop.org/CommonTypes/" name="BikeRepair" 
targetNamespace="http://www.djbikerepair.org/BikeRepairService/">


<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     SERVICE DEFINITION - A service groups a set of ports into
     a service unit.
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <vprop:property name="RepairID" type="xsd:RepairIDType"/>
    <import location="CommonTypes.xsd" namespace="http://www.djbikeshop.org/CommonTypes/"/>
    <service name="BikeRepairService">
    </service>
</definitions>
